version: "3"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - backend-net
    expose:
      - "8000"

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db-password
    secrets:
      - db-password
    volumes:
      - ./db-data:/var/lib/mysql
    networks:
      - db-net

  proxy:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./certs:/etc/nginx/certs
    ports:
      - "443:443"
    networks:
      - proxy-net
      - backend-net

networks:
  backend-net:
  db-net:
  proxy-net:

secrets:
  db-password:
    file: ./db-password.txt
